# Generated by Django 5.0.7 on 2024-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sort_id',
            field=models.IntegerField(default=9999, null=True),
        ),
    ]
