#!/bin/bash

# Error flags configuration for bash
set -o errexit
set -o pipefail
set -o nounset

# Launching migrations and the flask development server
python manage.py migrate
python manage.py runserver 0.0.0.0:8000