# Generated by Django 4.1.2 on 2023-04-12 21:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=90, scale=None, size=[500, 500], upload_to='cloneTwitter/media/post'),
        ),
    ]
