# Generated by Django 4.1.2 on 2023-01-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
